Add Russian translation
elfenware/obliviate pull request #28
Opened 2022-11-04 05:49 UTC by lenemter

And update other extra .po files

2022-11-07 04:42 UTC, dar5hak approved these changes

2022-12-02 16:28 UTC, dar5hak requested changes

2022-12-02 16:28 UTC, dar5hak commented on po/extra/es.po
> +msgstr "Adición: traducción en neerlandés (@Vistaus)"
```suggestion
msgstr "Adición: traducción en italiano (@ albanobattistella)"
```

2022-12-02 16:28 UTC, dar5hak commented on po/extra/es.po
>  msgstr "Adición: traducción en neerlandés (@Vistaus)"
```suggestion
msgstr "Adición: traducción en italiano (@ albanobattistella)"
```

2022-12-02 16:28 UTC, dar5hak commented on po/extra/fr.po
> +msgstr "Ajout : Traductions en néerlandais (@Vistaus)"
```suggestion
msgstr "Ajout : Traductions en italien (@albanobattistella)"
```

2022-12-02 16:28 UTC, dar5hak commented on po/extra/fr.po
>  msgstr "Ajout : Traductions en néerlandais (@Vistaus)"
```suggestion
msgstr "Ajout : Traductions en italien (@albanobattistella)"
```

2022-12-02 16:39 UTC, merged

2022-12-02 16:47 UTC, dar5hak commented
@lenemter Would you also be wiling to add Russian translations for future releases? If you would, I can add you to the translators group, where I can notify you in case of an upcoming update and you can get the translations in before I publish the update. Let me know if you are interested.

(No hard feelings if you don't want to.)

2022-12-03 06:50 UTC, lenemter commented
@dar5hak Yes I would. Send me instructions if I need to to do anything

2022-12-03 07:50 UTC, dar5hak commented
@lenemter Thank you! I sent you an invite to the team.